/* ORDER SERVICE LIST */
export const GET_ORDER_SERVICE_LIST = "GET_ORDER_SERVICE_LIST"
export const GET_ORDER_SERVICE_LIST_SUCCESS = "GET_ORDER_SERVICE_LIST_SUCCESS"
export const GET_ORDER_SERVICE_LIST_FAIL = "GET_ORDER_SERVICE_LIST_FAIL"

/* ORDER SERVICE LIST BY STATUS */
export const GET_ORDER_SERVICE_LIST_BY_STATUS = "GET_ORDER_SERVICE_LIST"
export const GET_ORDER_SERVICE_LIST_BY_STATUS_SUCCESS =
  "GET_ORDER_SERVICE_LIST_SUCCESS"
export const GET_ORDER_SERVICE_LIST_BY_STATUS_FAIL =
  "GET_ORDER_SERVICE_LIST_FAIL"

/* ORDER_SERVICE DETAIL */
export const GET_ORDER_SERVICE_DETAIL = "GET_ORDER_SERVICE_DETAIL"
export const GET_ORDER_SERVICE_DETAIL_SUCCESS =
  "GET_ORDER_SERVICE_DETAIL_SUCCESS"
export const GET_ORDER_SERVICE_DETAIL_FAIL = "GET_ORDER_SERVICE_DETAIL_FAIL"

/* RECOMMEND ORDER SERVICE  */
export const PUT_ORDER_SERVICE = "PUT_ORDER_SERVICE"
export const PUT_ORDER_SERVICE_SUCCESS = "PUT_ORDER_SERVICE_SUCCESS"
export const PUT_ORDER_SERVICE_FAIL = "PUT_ORDER_SERVICE_FAIL"

/* ASSIGN EXPERT */
export const PUT_ASSIGN_EXPERT = "PUT_ASSIGN_EXPERT"
export const PUT_ASSIGN_EXPERT_SUCCESS = "PUT_ASSIGN_EXPERT_SUCCESS"
export const PUT_ASSIGN_EXPERT_FAIL = "PUT_ASSIGN_EXPERT_FAIL"

/* STATUS LOG */
export const GET_STATUS_LOG = "GET_STATUS_LOG"
export const GET_STATUS_LOG_SUCCESS = "GET_STATUS_LOG_SUCCESS"
export const GET_STATUS_LOG_FAIL = "GET_STATUS_LOG_FAIL"

/* CONFIRM SERVICES */
export const PUT_CONFIRM_SERVICES = "PUT_CONFIRM_SERVICES"
export const PUT_CONFIRM_SERVICES_SUCCESS = "PUT_CONFIRM_SERVICES_SUCCESS"
export const PUT_CONFIRM_SERVICES_FAIL = "PUT_CONFIRM_SERVICES_FAIL"

/* CONFIRM & PAID SERVICES */
export const PUT_CONFIRM_PAID_SERVICES = "PUT_CONFIRM_PAID_SERVICES"
export const PUT_CONFIRM_PAID_SERVICES_SUCCESS =
  "PUT_CONFIRM_PAID_SERVICES_SUCCESS"
export const PUT_CONFIRM_PAID_SERVICES_FAIL = "PUT_CONFIRM_PAID_SERVICES_FAIL"

/* CHECKOUT */
export const POST_CHECKOUT_SERVICES = "POST_CHECKOUT_SERVICES"
export const POST_CHECKOUT_SERVICES_SUCCESS = "POST_CHECKOUT_SERVICES_SUCCESS"
export const POST_CHECKOUT_SERVICES_FAIL = "POST_CHECKOUT_SERVICES_FAIL"
